# Generated by Django 3.1.5 on 2021-09-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KeepItTidy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(default='item_name', max_length=200),
        ),
        migrations.DeleteModel(
            name='DescriptionField',
        ),
    ]
