# Generated by Django 3.1.5 on 2021-08-12 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KeepItTidy', '0002_collection_textfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='textfield',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='text_field', to='KeepItTidy.collection'),
        ),
    ]
