# Generated by Django 3.2.7 on 2021-09-14 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KeepItTidy', '0002_auto_20210907_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='BooleanField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('boolean', models.BooleanField(default=False)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boolean_field', to='KeepItTidy.collection')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boolean_field', to='KeepItTidy.item')),
            ],
        ),
    ]
