# Generated by Django 3.1.5 on 2021-08-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KeepItTidy', '0003_textfield_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='textfield',
            name='name',
            field=models.CharField(default='default_name', max_length=200),
            preserve_default=False,
        ),
    ]
