# Generated by Django 3.1.5 on 2021-08-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KeepItTidy', '0005_datefield_decimalfield_descriptionfield_numberfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datefield',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
