# Generated by Django 3.2.7 on 2021-11-10 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KeepItTidy', '0005_temptablefield'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TempTableField',
            new_name='TempTable',
        ),
    ]
