# Generated by Django 3.1.5 on 2021-08-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KeepItTidy', '0006_auto_20210825_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descriptionfield',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='numberfield',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
