# Generated by Django 3.1.5 on 2021-08-30 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KeepItTidy', '0007_auto_20210828_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection_fields', to='KeepItTidy.collection')),
            ],
        ),
        migrations.CreateModel(
            name='FieldNameTypePair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=200)),
                ('field_type', models.CharField(max_length=200)),
                ('dictionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_type_pair', to='KeepItTidy.fielddict')),
            ],
        ),
    ]
